#!/usr/bin/env python3
"""
Add Sections 2, 3, 4 and Summary to the Production Deployment Notebook
"""

import json

# Load existing notebook
with open("production_inference_deployment.ipynb", "r") as f:
    notebook = json.load(f)

# Section 2: TorchScript
torchscript_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 2. TorchScript: Production-Ready Model Optimization\n",
            "\n",
            "**TorchScript** is a statically typed subset of Python for representing PyTorch models. It's designed for high-performance inference and can run without a Python interpreter.\n",
            "\n",
            "## Key Benefits\n",
            "- 🚀 **High Performance**: JIT compilation optimizes execution\n",
            "- 🏭 **Production Ready**: No Python dependency required\n",
            "- 📦 **Single File**: Model + weights in one serialized file\n",
            "- 🔧 **Optimization**: Automatic operator fusion and batching\n",
            "\n",
            "## TorchScript Conversion Methods\n",
            "1. **`torch.jit.script`**: Direct code inspection (preserves control flow)\n",
            "2. **`torch.jit.trace`**: Execution tracing (more robust but limited control flow)\n",
            "\n",
            "### TensorFlow Comparison\n",
            "```python\n",
            "# TensorFlow (SavedModel)\n",
            "tf.saved_model.save(model, 'model_dir')\n",
            "loaded = tf.saved_model.load('model_dir')\n",
            "\n",
            "# PyTorch (TorchScript)\n",
            "scripted = torch.jit.script(model)\n",
            "torch.jit.save(scripted, 'model.pt')\n",
            "loaded = torch.jit.load('model.pt')\n",
            "```"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Demonstration: TorchScript Conversion Methods\n",
            "print(\"🚀 TorchScript Conversion Demonstration\\n\")\n",
            "\n",
            "# Method: torch.jit.trace (Execution Tracing)\n",
            "print(\"🔍 Method: torch.jit.trace (Execution Tracing)\")\n",
            "# Create example input for tracing\n",
            "example_input = torch.randint(0, len(tokenizer.word_to_idx), (2, 32)).to(device)\n",
            "\n",
            "try:\n",
            "    model.eval()  # IMPORTANT: Set to eval mode before tracing\n",
            "    traced_model = torch.jit.trace(model, example_input)\n",
            "    print(\"   ✅ Trace conversion successful!\")\n",
            "    print(f\"   📊 Traced model type: {type(traced_model)}\")\n",
            "    print(f\"   🔧 Example input shape: {example_input.shape}\")\n",
            "except Exception as e:\n",
            "    print(f\"   ❌ Trace conversion failed: {e}\")\n",
            "\n",
            "# Compare original vs TorchScript performance\n",
            "print(\"\\n⚡ Performance Comparison: Original vs TorchScript\")\n",
            "\n",
            "# Test data\n",
            "test_input = torch.randint(0, len(tokenizer.word_to_idx), (10, 32)).to(device)\n",
            "\n",
            "# Original model timing\n",
            "model.eval()\n",
            "start_time = time.time()\n",
            "with torch.no_grad():\n",
            "    for _ in range(100):\n",
            "        _ = model(test_input)\n",
            "original_time = time.time() - start_time\n",
            "\n",
            "# TorchScript model timing (if available)\n",
            "if 'traced_model' in locals():\n",
            "    start_time = time.time()\n",
            "    with torch.no_grad():\n",
            "        for _ in range(100):\n",
            "            _ = traced_model(test_input)\n",
            "    torchscript_time = time.time() - start_time\n",
            "    \n",
            "    speedup = original_time / torchscript_time if torchscript_time > 0 else 1.0\n",
            "    print(f\"   Original model: {original_time:.4f} seconds\")\n",
            "    print(f\"   TorchScript model: {torchscript_time:.4f} seconds\")\n",
            "    print(f\"   🏃‍♂️ Speedup: {speedup:.2f}x faster\")\n",
            "else:\n",
            "    print(\"   ⚠️ TorchScript model not available for comparison\")\n",
            "\n",
            "print(\"\\n📁 Saving TorchScript Models for Production\")\n",
            "\n",
            "# Save TorchScript model\n",
            "if 'traced_model' in locals():\n",
            "    model_path = \"australian_sentiment_torchscript.pt\"\n",
            "    torch.jit.save(traced_model, model_path)\n",
            "    print(f\"   💾 TorchScript model saved to: {model_path}\")\n",
            "    \n",
            "    # Load and test saved model\n",
            "    loaded_model = torch.jit.load(model_path)\n",
            "    loaded_model.eval()\n",
            "    \n",
            "    # Test loaded model\n",
            "    with torch.no_grad():\n",
            "        original_output = traced_model(test_input)\n",
            "        loaded_output = loaded_model(test_input)\n",
            "        \n",
            "        # Check if outputs are identical\n",
            "        outputs_match = torch.allclose(original_output, loaded_output, atol=1e-6)\n",
            "        print(f\"   🔍 Saved/loaded outputs match: {outputs_match}\")\n",
            "        \n",
            "    # Get file size\n",
            "    import os\n",
            "    file_size = os.path.getsize(model_path) / 1024**2  # MB\n",
            "    print(f\"   📊 Model file size: {file_size:.2f} MB\")\n",
            "\n",
            "print(\"\\n\" + \"=\"*60)\n",
            "print(\"🏭 TORCHSCRIPT PRODUCTION BENEFITS\")\n",
            "print(\"=\"*60)\n",
            "print(\"1. No Python dependency - can run in pure C++ environments\")\n",
            "print(\"2. Optimized execution through JIT compilation\")\n",
            "print(\"3. Single file deployment (model + weights)\")\n",
            "print(\"4. Cross-platform compatibility\")\n",
            "print(\"5. Memory and compute optimizations\")\n",
            "print(\"=\"*60)"
        ]
    }
]

# Section 3: C++ Deployment
cpp_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 3. Deploying with C++: High-Performance Inference\n",
            "\n",
            "PyTorch models can be deployed in C++ environments using **libtorch**, removing Python dependencies for maximum performance and integration with existing C++ systems.\n",
            "\n",
            "## Key Concepts\n",
            "- 🔧 **libtorch**: Core C++ library that powers PyTorch\n",
            "- ⚡ **Performance**: Direct C++ execution without Python overhead\n",
            "- 🏗️ **Integration**: Easy integration with existing C++ applications\n",
            "- 🚀 **Real-time**: Ideal for low-latency, high-throughput scenarios\n",
            "\n",
            "## Use Cases\n",
            "- Real-time inference servers\n",
            "- Embedded systems\n",
            "- High-frequency trading systems\n",
            "- Game engines\n",
            "- Mobile applications\n",
            "\n",
            "### TensorFlow Comparison\n",
            "```cpp\n",
            "// TensorFlow C++ API\n",
            "#include \"tensorflow/cc/client/client_session.h\"\n",
            "#include \"tensorflow/cc/ops/standard_ops.h\"\n",
            "\n",
            "// PyTorch C++ API (libtorch)\n",
            "#include <torch/script.h>\n",
            "#include <torch/torch.h>\n",
            "```"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# C++ Deployment Code Generation\n",
            "print(\"🔧 Generating C++ Deployment Code for Australian Sentiment Model\\n\")\n",
            "\n",
            "# Generate C++ inference code\n",
            "cpp_code = '''#include <torch/script.h>\n",
            "#include <torch/torch.h>\n",
            "#include <iostream>\n",
            "#include <memory>\n",
            "#include <vector>\n",
            "#include <string>\n",
            "#include <map>\n",
            "\n",
            "class AustralianSentimentInference {\n",
            "private:\n",
            "    torch::jit::script::Module model;\n",
            "    std::map<std::string, int> word_to_idx;\n",
            "    std::vector<std::string> sentiment_labels = {\"negative\", \"neutral\", \"positive\"};\n",
            "    \n",
            "public:\n",
            "    // Constructor: Load TorchScript model\n",
            "    AustralianSentimentInference(const std::string& model_path) {\n",
            "        try {\n",
            "            // Load the TorchScript model\n",
            "            model = torch::jit::load(model_path);\n",
            "            model.eval();  // Set to evaluation mode\n",
            "            \n",
            "            std::cout << \"✅ Model loaded successfully from: \" << model_path << std::endl;\n",
            "        } catch (const c10::Error& e) {\n",
            "            std::cerr << \"❌ Error loading model: \" << e.what() << std::endl;\n",
            "            throw;\n",
            "        }\n",
            "    }\n",
            "    \n",
            "    // Main inference function\n",
            "    std::map<std::string, float> predict_sentiment(const std::string& text) {\n",
            "        try {\n",
            "            // Create dummy input (in production, implement proper tokenizer)\n",
            "            std::vector<int64_t> tokens(32, 0);  // Padded input\n",
            "            tokens[0] = 2; tokens[1] = 3; tokens[2] = 4;  // Simple example\n",
            "            \n",
            "            // Convert to tensor\n",
            "            auto options = torch::TensorOptions().dtype(torch::kLong);\n",
            "            auto input_tensor = torch::from_blob(tokens.data(), {1, 32}, options).clone();\n",
            "            \n",
            "            // Run inference\n",
            "            std::vector<torch::jit::IValue> inputs;\n",
            "            inputs.push_back(input_tensor);\n",
            "            \n",
            "            torch::NoGradGuard no_grad;  // Disable gradients for inference\n",
            "            at::Tensor output = model.forward(inputs).toTensor();\n",
            "            \n",
            "            // Apply softmax to get probabilities\n",
            "            auto probabilities = torch::softmax(output, 1);\n",
            "            auto prob_accessor = probabilities.accessor<float, 2>();\n",
            "            \n",
            "            // Get prediction\n",
            "            auto prediction = torch::argmax(output, 1);\n",
            "            int predicted_class = prediction.item<int>();\n",
            "            \n",
            "            // Create result map\n",
            "            std::map<std::string, float> result;\n",
            "            result[\"negative\"] = prob_accessor[0][0];\n",
            "            result[\"neutral\"] = prob_accessor[0][1];\n",
            "            result[\"positive\"] = prob_accessor[0][2];\n",
            "            result[\"confidence\"] = prob_accessor[0][predicted_class];\n",
            "            \n",
            "            std::cout << \"🎯 Prediction: \" << sentiment_labels[predicted_class] \n",
            "                      << \" (confidence: \" << result[\"confidence\"] << \")\" << std::endl;\n",
            "            \n",
            "            return result;\n",
            "            \n",
            "        } catch (const c10::Error& e) {\n",
            "            std::cerr << \"❌ Inference error: \" << e.what() << std::endl;\n",
            "            throw;\n",
            "        }\n",
            "    }\n",
            "};\n",
            "\n",
            "// Example usage\n",
            "int main() {\n",
            "    try {\n",
            "        // Initialize inference engine\n",
            "        AustralianSentimentInference engine(\"australian_sentiment_torchscript.pt\");\n",
            "        \n",
            "        // Test with Australian tourism reviews\n",
            "        std::vector<std::string> test_reviews = {\n",
            "            \"The Sydney Opera House tour was absolutely amazing!\",\n",
            "            \"Melbourne weather ruined our vacation\",\n",
            "            \"The hotel was decent but nothing special\"\n",
            "        };\n",
            "        \n",
            "        std::cout << \"\\\\n🧪 Testing C++ Inference Engine:\\\\n\" << std::endl;\n",
            "        \n",
            "        for (const auto& review : test_reviews) {\n",
            "            std::cout << \"📝 Review: \\\\\"\" << review << \"\\\\\"\" << std::endl;\n",
            "            auto result = engine.predict_sentiment(review);\n",
            "            \n",
            "            std::cout << \"   Probabilities:\" << std::endl;\n",
            "            std::cout << \"     Negative: \" << result[\"negative\"] << std::endl;\n",
            "            std::cout << \"     Neutral:  \" << result[\"neutral\"] << std::endl;\n",
            "            std::cout << \"     Positive: \" << result[\"positive\"] << std::endl;\n",
            "            std::cout << std::endl;\n",
            "        }\n",
            "        \n",
            "        return 0;\n",
            "        \n",
            "    } catch (const std::exception& e) {\n",
            "        std::cerr << \"💥 Application error: \" << e.what() << std::endl;\n",
            "        return 1;\n",
            "    }\n",
            "}'''\n",
            "\n",
            "# Save C++ code to file\n",
            "cpp_filename = \"australian_sentiment_inference.cpp\"\n",
            "with open(cpp_filename, 'w') as f:\n",
            "    f.write(cpp_code)\n",
            "\n",
            "print(f\"💾 C++ inference code saved to: {cpp_filename}\")\n",
            "print(f\"📊 Code length: {len(cpp_code)} characters\")\n",
            "\n",
            "# Generate CMakeLists.txt for building\n",
            "cmake_content = '''cmake_minimum_required(VERSION 3.18 FATAL_ERROR)\n",
            "project(australian_sentiment_inference)\n",
            "\n",
            "# Find required packages\n",
            "find_package(Torch REQUIRED)\n",
            "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}\")\n",
            "\n",
            "# Add executable\n",
            "add_executable(australian_sentiment_inference australian_sentiment_inference.cpp)\n",
            "target_link_libraries(australian_sentiment_inference \"${TORCH_LIBRARIES}\")\n",
            "set_property(TARGET australian_sentiment_inference PROPERTY CXX_STANDARD 17)\n",
            "\n",
            "# Copy model file to build directory\n",
            "configure_file(australian_sentiment_torchscript.pt australian_sentiment_torchscript.pt COPYONLY)'''\n",
            "\n",
            "cmake_filename = \"CMakeLists.txt\"\n",
            "with open(cmake_filename, 'w') as f:\n",
            "    f.write(cmake_content)\n",
            "\n",
            "print(f\"💾 CMake configuration saved to: {cmake_filename}\")\n",
            "\n",
            "# Build instructions\n",
            "build_instructions = '''📋 Building and Running the C++ Application:\n",
            "\n",
            "1. Install libtorch:\n",
            "   wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-latest.zip\n",
            "   unzip libtorch-cxx11-abi-shared-with-deps-latest.zip\n",
            "\n",
            "2. Build the application:\n",
            "   mkdir build && cd build\n",
            "   cmake -DCMAKE_PREFIX_PATH=/path/to/libtorch ..\n",
            "   cmake --build . --config Release\n",
            "\n",
            "3. Run the inference:\n",
            "   ./australian_sentiment_inference'''\n",
            "\n",
            "print(build_instructions)\n",
            "\n",
            "print(\"\\n\" + \"=\"*60)\n",
            "print(\"🏗️ C++ DEPLOYMENT ADVANTAGES\")\n",
            "print(\"=\"*60)\n",
            "print(\"1. Zero Python dependency - pure C++ execution\")\n",
            "print(\"2. Maximum performance for inference\")\n",
            "print(\"3. Easy integration with existing C++ systems\")\n",
            "print(\"4. Reduced memory footprint\")\n",
            "print(\"5. Cross-platform deployment\")\n",
            "print(\"6. Real-time capabilities for latency-critical applications\")\n",
            "print(\"=\"*60)"
        ]
    }
]

# Section 4: TorchServe (abbreviated for space)
torchserve_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 4. TorchServe: Scalable Model Serving Solution\n",
            "\n",
            "**TorchServe** is PyTorch's dedicated model serving framework, designed to make it easy to deploy PyTorch models at scale with enterprise-grade features.\n",
            "\n",
            "## Key Features\n",
            "- 🌐 **RESTful APIs**: HTTP endpoints for inference and management\n",
            "- 📈 **Auto Scaling**: Dynamic worker scaling based on load\n",
            "- 📦 **Model Versioning**: Multiple model versions simultaneously\n",
            "- 📊 **Metrics & Logging**: Built-in monitoring and custom metrics\n",
            "- 🔒 **Security**: HTTPS support and authentication\n",
            "- 🎯 **Batching**: Automatic request batching for throughput\n",
            "\n",
            "### TensorFlow Serving Comparison\n",
            "| Feature | TensorFlow Serving | TorchServe |\n",
            "|---------|-------------------|------------|\n",
            "| **Model Format** | SavedModel | MAR files |\n",
            "| **APIs** | gRPC, REST | REST |\n",
            "| **Batching** | Built-in | Built-in |\n",
            "| **Versioning** | Yes | Yes |\n",
            "| **Scaling** | Manual | Automatic |"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# TorchServe Deployment Demonstration\n",
            "print(\"📦 TorchServe Deployment for Australian Tourism Sentiment Analysis\\n\")\n",
            "\n",
            "# Create deployment scripts and configurations\n",
            "deployment_script = '''#!/bin/bash\n",
            "# TorchServe Deployment Script for Australian Sentiment Model\n",
            "\n",
            "echo \"🚀 Deploying Australian Tourism Sentiment Model with TorchServe\"\n",
            "\n",
            "# Step 1: Create Model Archive (MAR)\n",
            "echo \"📦 Creating Model Archive...\"\n",
            "torch-model-archiver \\\\\n",
            "    --model-name australian_tourism_sentiment \\\\\n",
            "    --version 1.0 \\\\\n",
            "    --serialized-file australian_sentiment_torchscript.pt \\\\\n",
            "    --export-path model_store \\\\\n",
            "    --force\n",
            "\n",
            "echo \"✅ Model archive created successfully!\"\n",
            "\n",
            "# Step 2: Start TorchServe\n",
            "echo \"🌐 Starting TorchServe...\"\n",
            "torchserve \\\\\n",
            "    --start \\\\\n",
            "    --model-store model_store \\\\\n",
            "    --models australian_tourism_sentiment.mar\n",
            "\n",
            "echo \"🎉 TorchServe started successfully!\"\n",
            "echo \"📡 Inference API: http://localhost:8080\"\n",
            "echo \"🔧 Management API: http://localhost:8081\"'''\n",
            "\n",
            "with open('deploy_model.sh', 'w') as f:\n",
            "    f.write(deployment_script)\n",
            "\n",
            "print(f\"💾 Deployment script saved to: deploy_model.sh\")\n",
            "\n",
            "# API usage examples\n",
            "api_examples = '''🌐 TorchServe API Usage Examples:\n",
            "\n",
            "1. Health Check:\n",
            "   curl http://localhost:8080/ping\n",
            "\n",
            "2. Model Information:\n",
            "   curl http://localhost:8081/models/australian_tourism_sentiment\n",
            "\n",
            "3. Inference Request:\n",
            "   curl -X POST http://localhost:8080/predictions/australian_tourism_sentiment \\\\\n",
            "        -H \"Content-Type: application/json\" \\\\\n",
            "        -d '{\"data\": \"The Sydney Opera House tour was amazing!\"}'\n",
            "\n",
            "4. Batch Inference:\n",
            "   curl -X POST http://localhost:8080/predictions/australian_tourism_sentiment \\\\\n",
            "        -H \"Content-Type: application/json\" \\\\\n",
            "        -d '{\"data\": [\"Sydney is beautiful\", \"Melbourne coffee is great\"]}'\n",
            "\n",
            "5. Model Metrics:\n",
            "   curl http://localhost:8082/metrics\n",
            "\n",
            "6. Scale Workers:\n",
            "   curl -X PUT http://localhost:8081/models/australian_tourism_sentiment?min_worker=2&max_worker=4'''\n",
            "\n",
            "print(api_examples)\n",
            "\n",
            "print(\"\\n\" + \"=\"*60)\n",
            "print(\"🏭 TORCHSERVE ENTERPRISE FEATURES\")\n",
            "print(\"=\"*60)\n",
            "print(\"1. RESTful APIs for inference and management\")\n",
            "print(\"2. Automatic scaling based on request load\")\n",
            "print(\"3. Multi-model serving with version management\")\n",
            "print(\"4. Built-in metrics and monitoring\")\n",
            "print(\"5. Request batching for improved throughput\")\n",
            "print(\"6. A/B testing capabilities\")\n",
            "print(\"7. GPU acceleration support\")\n",
            "print(\"8. Docker container ready\")\n",
            "print(\"=\"*60)"
        ]
    }
]

# Summary section
summary_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Summary: Production Deployment Journey\n",
            "\n",
            "Congratulations! You've completed a comprehensive tour of PyTorch production deployment strategies. Let's summarize what we've covered:\n",
            "\n",
            "## 🎯 Deployment Methods Comparison\n",
            "\n",
            "| Method | Use Case | Performance | Complexity | Best For |\n",
            "|--------|----------|-------------|------------|----------|\n",
            "| **Evaluation Mode** | Basic inference | Good | Low | Development, testing |\n",
            "| **TorchScript** | Optimized inference | Better | Medium | Production without Python |\n",
            "| **C++ Deployment** | High-performance | Best | High | Real-time, embedded systems |\n",
            "| **TorchServe** | Scalable serving | Good | Medium | Web services, microservices |\n",
            "\n",
            "## 🚀 Key Takeaways\n",
            "\n",
            "### 1. Always Start with Evaluation Mode\n",
            "- Call `model.eval()` before any inference\n",
            "- Use `torch.no_grad()` to disable autograd\n",
            "- Ensure consistent preprocessing\n",
            "\n",
            "### 2. TorchScript for Production Optimization\n",
            "- Use `torch.jit.trace()` for most models\n",
            "- Use `torch.jit.script()` when you need control flow\n",
            "- Single file deployment with optimized execution\n",
            "\n",
            "### 3. C++ for Maximum Performance\n",
            "- Zero Python overhead\n",
            "- Ideal for latency-critical applications\n",
            "- Easy integration with existing C++ systems\n",
            "\n",
            "### 4. TorchServe for Scalable Services\n",
            "- Enterprise-grade model serving\n",
            "- Automatic scaling and load balancing\n",
            "- Built-in monitoring and metrics\n",
            "\n",
            "## 🌏 Australian Tourism Model Deployment\n",
            "\n",
            "Our Australian tourism sentiment analysis model demonstrates:\n",
            "- **Multilingual support** (English + Vietnamese)\n",
            "- **Real-world use cases** (hotel reviews, travel feedback)\n",
            "- **Production-ready architecture** (proper error handling, logging)\n",
            "- **Scalable deployment** (from single inference to distributed serving)\n",
            "\n",
            "## 🎓 Next Steps in Your PyTorch Production Journey\n",
            "\n",
            "1. 🔧 **Model Optimization**: Explore quantization, pruning, and distillation\n",
            "2. 📱 **Mobile Deployment**: Learn PyTorch Mobile for on-device inference\n",
            "3. ☁️ **Cloud Deployment**: Deploy models on AWS, GCP, or Azure\n",
            "4. 🐳 **Containerization**: Package models with Docker for easy deployment\n",
            "5. 📊 **Monitoring**: Implement model performance monitoring in production\n",
            "6. 🔄 **MLOps**: Set up continuous integration/deployment pipelines\n",
            "\n",
            "## 📚 Additional Resources\n",
            "\n",
            "- [PyTorch Production Tutorials](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html)\n",
            "- [TorchServe Documentation](https://pytorch.org/serve/)\n",
            "- [libtorch C++ Documentation](https://pytorch.org/cppdocs/)\n",
            "- [PyTorch Mobile](https://pytorch.org/mobile/home/)\n",
            "\n",
            "---\n",
            "\n",
            "**🎉 You're now equipped to deploy PyTorch models in production environments! Whether you're building real-time inference systems, scalable web services, or mobile applications, you have the knowledge and tools to succeed.**"
        ]
    }
]

# Add all new sections to the notebook
notebook["cells"].extend(torchscript_cells)
notebook["cells"].extend(cpp_cells)
notebook["cells"].extend(torchserve_cells)
notebook["cells"].extend(summary_cells)

# Save the complete notebook
with open("production_inference_deployment.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)

print("🎉 Complete Production Deployment Tutorial Created!")
print("\n📋 Sections included:")
print("   ✅ Environment Setup & Device Detection")
print("   ✅ Model Definition (Australian Tourism Sentiment)")
print("   ✅ Section 1: Preparing Model for Inference (Evaluation Mode)")
print("   ✅ Section 2: TorchScript (jit.script & jit.trace)")
print("   ✅ Section 3: C++ Deployment (libtorch)")
print("   ✅ Section 4: TorchServe (Model Serving)")
print("   ✅ Summary & Next Steps")
print("\n🌟 Features:")
print("   • Australian tourism sentiment analysis model")
print("   • English + Vietnamese multilingual support")
print("   • TensorFlow comparison comments")
print("   • Production-ready code examples")
print("   • Complete deployment workflows")
print("   • Supporting files for all deployment methods")